// ============================================================
// NEXUS ROBOTECHPRO — Core Data Store
// All product, solution, case study and navigation data
// ============================================================

export const PRODUCTS = [
  {
    id: "surgical-robots",
    name: "Surgical Robots",
    shortName: "Surgical",
    tagline: "Precision Beyond Human Limits",
    description: "FDA & CE certified surgical robotic systems designed for minimally invasive procedures. Sub-millimeter accuracy with haptic feedback and AI-assisted navigation.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663470022895/2VJcLxvpuPkUTryZZjUQgV/surgical-robot-product-PXJvLojBQaiipKssVBFEea.webp",
    category: "Medical",
    certifications: ["FDA", "CE", "ISO 13485"],
    applications: ["Minimally Invasive Surgery", "Orthopedic Surgery", "Neurosurgery", "Laparoscopic Procedures"],
    specs: [
      { label: "Positioning Accuracy", value: "±0.1mm" },
      { label: "DOF", value: "7-axis" },
      { label: "Payload", value: "5 kg" },
      { label: "Reach", value: "850 mm" },
      { label: "Certification", value: "FDA / CE" },
      { label: "Control Latency", value: "<10ms" },
    ],
    models: ["NRT-S100", "NRT-S200 Pro", "NRT-S300 Elite"],
    icon: "🏥",
    color: "from-blue-600 to-cyan-500",
  },
  {
    id: "robot-dogs",
    name: "Robot Dogs",
    shortName: "Quadruped",
    tagline: "Autonomous Intelligence, Unmatched Mobility",
    description: "Advanced quadruped robots for research, security patrol, and hazardous environment inspection. All-terrain capability with AI perception and autonomous navigation.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663470022895/2VJcLxvpuPkUTryZZjUQgV/robot-dog-product-JEZxSKzm82TDWqMnyNdFo2.webp",
    category: "Research & Security",
    certifications: ["CE", "FCC", "RoHS"],
    applications: ["Security Patrol", "Research & Education", "Hazardous Inspection", "Search & Rescue"],
    specs: [
      { label: "Max Speed", value: "3.5 m/s" },
      { label: "Payload", value: "15 kg" },
      { label: "Battery Life", value: "4 hours" },
      { label: "IP Rating", value: "IP67" },
      { label: "Sensors", value: "LIDAR + Stereo" },
      { label: "Weight", value: "32 kg" },
    ],
    models: ["NRD-Q1", "NRD-Q2 Pro", "NRD-Q3 Tactical"],
    icon: "🐕",
    color: "from-slate-600 to-blue-600",
  },
  {
    id: "cooking-robots",
    name: "Cooking Robots",
    shortName: "Culinary",
    tagline: "Consistent Quality, Infinite Scale",
    description: "Automated culinary robots for restaurant chains and central kitchens. Programmable recipes, consistent output, and food-grade certified components.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    category: "Food & Catering",
    certifications: ["CE", "NSF", "Food Grade"],
    applications: ["Restaurant Chains", "Central Kitchens", "Hotel Catering", "Food Processing"],
    specs: [
      { label: "Cooking Speed", value: "120 dishes/hr" },
      { label: "Recipe Storage", value: "10,000+" },
      { label: "Temperature Range", value: "0–300°C" },
      { label: "Cleaning Cycle", value: "Auto 15min" },
      { label: "Footprint", value: "1.2m × 0.8m" },
      { label: "Power", value: "380V / 15kW" },
    ],
    models: ["NRC-C100", "NRC-C200 Chef", "NRC-C300 Industrial"],
    icon: "🍳",
    color: "from-orange-600 to-amber-500",
  },
  {
    id: "welding-robots",
    name: "Arc Welding Robotic Arms",
    shortName: "Welding",
    tagline: "Industrial Precision, Zero Compromise",
    description: "High-performance arc welding robotic arms for manufacturing. Superior weld quality with adaptive seam tracking, multi-process capability, and Industry 4.0 integration.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663470022895/2VJcLxvpuPkUTryZZjUQgV/welding-robot-product-k7EY2QvgWTcQTDbNDPyRJz.webp",
    category: "Manufacturing",
    certifications: ["CE", "ISO 9001", "AWS"],
    applications: ["Automotive Manufacturing", "Steel Fabrication", "Shipbuilding", "Aerospace Components"],
    specs: [
      { label: "Payload", value: "20 kg" },
      { label: "Reach", value: "1850 mm" },
      { label: "Repeatability", value: "±0.05mm" },
      { label: "Welding Processes", value: "MIG/MAG/TIG" },
      { label: "IP Rating", value: "IP65" },
      { label: "Axes", value: "6-axis" },
    ],
    models: ["NRW-A100", "NRW-A200 Heavy", "NRW-A300 Precision"],
    icon: "⚡",
    color: "from-orange-700 to-red-600",
  },
  {
    id: "special-robots",
    name: "Special Robots",
    shortName: "Special",
    tagline: "Custom Solutions for Extreme Environments",
    description: "Purpose-built robots for special scenarios including nuclear inspection, underwater operations, high-altitude maintenance, and disaster response.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
    category: "Special Scenarios",
    certifications: ["CE", "ATEX", "Custom"],
    applications: ["Nuclear Inspection", "Underwater Operations", "High-Altitude Maintenance", "Disaster Response"],
    specs: [
      { label: "Operating Temp", value: "-40°C to 80°C" },
      { label: "Depth Rating", value: "300m (aquatic)" },
      { label: "Radiation Tolerance", value: "Up to 1000 Gy" },
      { label: "Customization", value: "Full OEM" },
      { label: "Lead Time", value: "12–16 weeks" },
      { label: "Warranty", value: "2 years" },
    ],
    models: ["NRS-X100 Custom", "NRS-X200 Aqua", "NRS-X300 Hazmat"],
    icon: "🔬",
    color: "from-purple-600 to-blue-600",
  },
  {
    id: "exoskeletons",
    name: "Exoskeletons",
    shortName: "Exo",
    tagline: "Augmenting Human Capability",
    description: "Wearable robotic exoskeletons for rehabilitation and industrial applications. Lightweight carbon fiber structure with adaptive AI control for natural movement assistance.",
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80",
    category: "Rehabilitation & Industrial",
    certifications: ["CE", "FDA", "ISO 13485"],
    applications: ["Physical Rehabilitation", "Industrial Labor Assistance", "Military Applications", "Elderly Care"],
    specs: [
      { label: "Weight", value: "8.5 kg" },
      { label: "Load Assistance", value: "40 kg" },
      { label: "Battery Life", value: "8 hours" },
      { label: "Joints Supported", value: "Hip, Knee, Ankle" },
      { label: "Material", value: "Carbon Fiber" },
      { label: "Connectivity", value: "BLE 5.0 + WiFi" },
    ],
    models: ["NRE-E100 Rehab", "NRE-E200 Industrial", "NRE-E300 Military"],
    icon: "🦾",
    color: "from-teal-600 to-cyan-500",
  },
  {
    id: "delivery-robots",
    name: "Delivery Robots",
    shortName: "Delivery",
    tagline: "Last-Mile Automation, Perfected",
    description: "Autonomous delivery robots for indoor and outdoor logistics. SLAM navigation, obstacle avoidance, and fleet management system for seamless last-mile delivery.",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    category: "Logistics",
    certifications: ["CE", "FCC", "UL"],
    applications: ["Hotel Room Service", "Hospital Logistics", "Restaurant Delivery", "Office Supply"],
    specs: [
      { label: "Payload", value: "30 kg" },
      { label: "Max Speed", value: "1.5 m/s" },
      { label: "Battery Life", value: "10 hours" },
      { label: "Navigation", value: "SLAM + AI" },
      { label: "Obstacle Avoidance", value: "360° LiDAR" },
      { label: "Elevator Compatible", value: "Yes" },
    ],
    models: ["NRD-D100", "NRD-D200 Plus", "NRD-D300 Outdoor"],
    icon: "📦",
    color: "from-green-600 to-teal-500",
  },
  {
    id: "robot-parts",
    name: "Robot Parts",
    shortName: "Parts",
    tagline: "OEM Supply, Global Distribution",
    description: "Comprehensive robot components supply for distributors and OEM manufacturers. Servo motors, controllers, sensors, end-effectors, and structural components with global logistics.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    category: "Components",
    certifications: ["CE", "RoHS", "ISO 9001"],
    applications: ["OEM Manufacturing", "Maintenance & Repair", "Research Prototyping", "System Integration"],
    specs: [
      { label: "SKU Count", value: "50,000+" },
      { label: "MOQ", value: "1 unit" },
      { label: "Lead Time", value: "3–7 days" },
      { label: "Warranty", value: "12 months" },
      { label: "Shipping", value: "Global DDP" },
      { label: "Certifications", value: "CE / RoHS" },
    ],
    models: ["Servo Motors", "Controllers", "Sensors & Vision", "End Effectors"],
    icon: "⚙️",
    color: "from-gray-600 to-slate-500",
  },
];

export const SOLUTIONS = [
  {
    id: "medical-healthcare",
    name: "Medical & Healthcare",
    icon: "🏥",
    description: "Transforming surgical precision and patient outcomes with FDA/CE certified robotic systems.",
    painPoints: ["High surgical error rates", "Surgeon fatigue in long procedures", "Limited access to specialist surgeons", "Rising healthcare costs"],
    products: ["surgical-robots", "exoskeletons", "delivery-robots"],
    metrics: [
      { value: "40%", label: "Reduction in surgical complications" },
      { value: "60%", label: "Faster patient recovery" },
      { value: "99.9%", label: "Positioning accuracy" },
    ],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
  },
  {
    id: "research-security",
    name: "Research & Security",
    icon: "🔬",
    description: "Empowering research institutions and security operations with autonomous robotic platforms.",
    painPoints: ["Dangerous environment access", "24/7 patrol requirements", "Data collection in remote areas", "High personnel costs"],
    products: ["robot-dogs", "special-robots"],
    metrics: [
      { value: "24/7", label: "Autonomous patrol coverage" },
      { value: "300m", label: "Operational depth range" },
      { value: "50+", label: "Universities deployed" },
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
  },
  {
    id: "food-catering",
    name: "Food & Catering",
    icon: "🍳",
    description: "Consistent quality and scalable production for restaurant chains and central kitchens.",
    painPoints: ["Labor shortage in kitchens", "Inconsistent food quality", "High food waste", "Difficulty scaling operations"],
    products: ["cooking-robots"],
    metrics: [
      { value: "35%", label: "Reduction in labor costs" },
      { value: "99%", label: "Recipe consistency rate" },
      { value: "120+", label: "Dishes per hour capacity" },
    ],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  },
  {
    id: "manufacturing-welding",
    name: "Manufacturing & Welding",
    icon: "⚡",
    description: "Elevating production quality and throughput with precision arc welding automation.",
    painPoints: ["Inconsistent weld quality", "Welder shortage globally", "Hazardous working conditions", "Production bottlenecks"],
    products: ["welding-robots", "robot-parts"],
    metrics: [
      { value: "±0.05mm", label: "Welding repeatability" },
      { value: "3x", label: "Production speed increase" },
      { value: "98%", label: "First-pass quality rate" },
    ],
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
  },
  {
    id: "logistics-delivery",
    name: "Logistics & Delivery",
    icon: "📦",
    description: "Automating last-mile delivery for hotels, hospitals, and commercial facilities.",
    painPoints: ["Rising delivery labor costs", "Inconsistent service times", "High turnover in delivery staff", "Multi-floor logistics complexity"],
    products: ["delivery-robots"],
    metrics: [
      { value: "10hr", label: "Continuous operation time" },
      { value: "30kg", label: "Maximum payload capacity" },
      { value: "500+", label: "Hotels & hospitals deployed" },
    ],
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
  },
  {
    id: "rehabilitation-exoskeleton",
    name: "Rehabilitation & Industrial Exoskeleton",
    icon: "🦾",
    description: "Restoring mobility for patients and enhancing worker capability in demanding environments.",
    painPoints: ["Slow rehabilitation progress", "Worker injury from heavy lifting", "High physiotherapy costs", "Limited mobility assistance options"],
    products: ["exoskeletons"],
    metrics: [
      { value: "40kg", label: "Load assistance capability" },
      { value: "8hr", label: "Battery life per charge" },
      { value: "60%", label: "Faster rehabilitation outcomes" },
    ],
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80",
  },
  {
    id: "robot-parts-supply",
    name: "Robot Parts Supply",
    icon: "⚙️",
    description: "Comprehensive OEM component supply chain for global distributors and system integrators.",
    painPoints: ["Long lead times for components", "Quality inconsistency from multiple suppliers", "Complex import/export logistics", "Limited technical support"],
    products: ["robot-parts"],
    metrics: [
      { value: "50K+", label: "SKUs in stock" },
      { value: "3-7", label: "Days global delivery" },
      { value: "120+", label: "Countries served" },
    ],
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
  },
];

export const CASE_STUDIES = [
  {
    id: "beijing-hospital-surgical",
    title: "Beijing General Hospital — Surgical Robot Deployment",
    industry: "Medical",
    customer: "Beijing General Hospital",
    location: "Beijing, China",
    product: "surgical-robots",
    challenge: "The hospital needed to expand minimally invasive surgical capabilities while reducing procedure time and improving patient outcomes.",
    solution: "Deployed 3 units of NRT-S200 Pro surgical robots across orthopedic and general surgery departments.",
    results: ["42% reduction in average procedure time", "Zero major complications in 1,200+ procedures", "Patient satisfaction score increased to 96%"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    testimonial: "The Nexus surgical system has fundamentally changed how we approach complex procedures.",
    testimonialAuthor: "Dr. Zhang Wei, Chief of Surgery",
  },
  {
    id: "mit-robot-dog-research",
    title: "MIT Robotics Lab — Quadruped Research Platform",
    industry: "Research",
    customer: "MIT Robotics Laboratory",
    location: "Cambridge, USA",
    product: "robot-dogs",
    challenge: "Required a robust, programmable quadruped platform for AI locomotion research in unstructured environments.",
    solution: "Supplied 12 NRD-Q2 Pro units with custom SDK integration and extended sensor packages.",
    results: ["Published 8 peer-reviewed papers using the platform", "Achieved record-breaking terrain navigation benchmarks", "Platform adopted by 3 additional universities"],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    testimonial: "The reliability and programmability of the Nexus robot dog is unmatched in the research market.",
    testimonialAuthor: "Prof. Sarah Chen, Robotics Lab Director",
  },
  {
    id: "haidilao-cooking-robot",
    title: "Haidilao Chain — Central Kitchen Automation",
    industry: "Food",
    customer: "Haidilao Restaurant Group",
    location: "Shanghai, China",
    product: "cooking-robots",
    challenge: "Needed to standardize food preparation across 200+ locations while reducing kitchen labor costs.",
    solution: "Installed NRC-C200 Chef systems in 15 central kitchens serving the entire restaurant network.",
    results: ["35% reduction in kitchen labor costs", "99.2% recipe consistency across all locations", "ROI achieved within 18 months"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    testimonial: "Our customers can't tell the difference — and that's exactly the point.",
    testimonialAuthor: "Operations Director, Haidilao Group",
  },
  {
    id: "bmw-welding-automation",
    title: "BMW Manufacturing — Welding Line Automation",
    industry: "Manufacturing",
    customer: "BMW Manufacturing Plant",
    location: "Munich, Germany",
    product: "welding-robots",
    challenge: "Required high-precision welding automation for new EV chassis production line with tight tolerances.",
    solution: "Deployed 48 NRW-A200 Heavy units integrated with existing BMW production management systems.",
    results: ["±0.05mm weld repeatability achieved", "Production throughput increased by 280%", "Zero quality recalls in first year of operation"],
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    testimonial: "Nexus welding robots exceeded our precision requirements for EV chassis production.",
    testimonialAuthor: "Production Manager, BMW Munich Plant",
  },
  {
    id: "marriott-delivery-robot",
    title: "Marriott Hotels — In-Room Delivery Automation",
    industry: "Logistics",
    customer: "Marriott International",
    location: "Multiple Locations",
    product: "delivery-robots",
    challenge: "Sought to automate in-room delivery service to reduce labor costs and improve guest experience.",
    solution: "Deployed NRD-D200 Plus fleet across 12 flagship properties with custom hotel management integration.",
    results: ["60% reduction in delivery labor costs", "Guest satisfaction scores up 18%", "Expanded to 12 additional properties within 6 months"],
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    testimonial: "Our guests love the novelty, and our operations team loves the efficiency.",
    testimonialAuthor: "VP Operations, Marriott Asia Pacific",
  },
];

export const CERTIFICATIONS = [
  { name: "FDA 510(k)", description: "US Food & Drug Administration clearance for medical devices", category: "Medical" },
  { name: "CE Mark", description: "European Conformity — safety, health, and environmental standards", category: "Global" },
  { name: "ISO 9001:2015", description: "Quality Management Systems certification", category: "Quality" },
  { name: "ISO 13485:2016", description: "Medical devices quality management systems", category: "Medical" },
  { name: "ISO 45001", description: "Occupational health and safety management", category: "Safety" },
  { name: "RoHS", description: "Restriction of Hazardous Substances compliance", category: "Environmental" },
  { name: "FCC", description: "Federal Communications Commission certification for US market", category: "Communications" },
  { name: "ATEX", description: "Explosive atmospheres equipment certification", category: "Special" },
];

export const COMPANY_STATS = [
  { value: "2008", label: "Founded", suffix: "" },
  { value: "50", label: "Countries Served", suffix: "+" },
  { value: "10000", label: "Robots Deployed", suffix: "+" },
  { value: "300", label: "R&D Engineers", suffix: "+" },
  { value: "120", label: "Global Patents", suffix: "+" },
  { value: "99.6", label: "Customer Satisfaction", suffix: "%" },
];

export const NAV_ITEMS = [
  {
    label: "Products",
    href: "/products",
    children: PRODUCTS.map(p => ({ label: p.name, href: `/products/${p.id}` })),
  },
  {
    label: "Solutions",
    href: "/solutions",
    children: SOLUTIONS.map(s => ({ label: s.name, href: `/solutions/${s.id}` })),
  },
  {
    label: "Case Studies",
    href: "/cases",
    children: [
      { label: "Medical Cases", href: "/cases?industry=Medical" },
      { label: "Research & Security", href: "/cases?industry=Research" },
      { label: "Food & Catering", href: "/cases?industry=Food" },
      { label: "Manufacturing", href: "/cases?industry=Manufacturing" },
      { label: "Logistics", href: "/cases?industry=Logistics" },
    ],
  },
  {
    label: "About Us",
    href: "/about",
    children: [
      { label: "Company Profile", href: "/about#company" },
      { label: "Factory & Production", href: "/about#factory" },
      { label: "Certifications", href: "/about#certifications" },
      { label: "Team & R&D", href: "/about#team" },
    ],
  },
  {
    label: "Resources",
    href: "/resources",
    children: [
      { label: "Product Manuals", href: "/resources#manuals" },
      { label: "CAD Drawings", href: "/resources#cad" },
      { label: "Technical Documents", href: "/resources#technical" },
      { label: "Blog & Insights", href: "/resources/blog" },
      { label: "Videos", href: "/resources#videos" },
    ],
  },
  {
    label: "Support",
    href: "/support",
    children: [
      { label: "Technical Consultation", href: "/support#consultation" },
      { label: "After-Sales Service", href: "/support#aftersales" },
      { label: "FAQs", href: "/support#faq" },
    ],
  },
  { label: "Contact Us", href: "/contact" },
  { label: "Dealer & Agent", href: "/dealer" },
];
